##############################################################################
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################

name: Fair CI

on:
  push:
    branches: [ main ]
  pull_request_target:
    branches:
      - '*'
  schedule:
    - cron: '0 0,12 * * *'

jobs:
  ci-linux:
    runs-on: ubuntu-latest 
    timeout-minutes: 10

    steps:
      - name: Install Swift 5.5
        uses: marcprux/setup-swift@main
        with:
          swift-version: "5.5"

      - name: Get swift version
        run: swift --version # Swift 5.5?

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run fairtool
        run: |
          swift run fairtool welcome

      - name: Fair Tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: swift test

  ci-macOS:
    # runs-on: linux # TODO: Swift 5.5; maybe dev1an/setup-swift@swift-5.5
    runs-on: macos-11
    env:
      #DEVELOPER_DIR: /Applications/Xcode_13.0.app/Contents/Developer
      DEVELOPER_DIR: /Applications/Xcode_13.0_beta.app/Contents/Developer
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run fairtool
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: xcrun swift run fairtool welcome

      - name: Fair Tests
        run: xcrun swift test
 
      - name: Test iOS FairCore
        if: false # not configured for testing
        run: xcodebuild test -configuration Debug -scheme "FairCore" -sdk "iphonesimulator" -destination "platform=iOS Simulator,name=iPad (8th generation)" 

      - name: Build iOS FairApp
        run: xcodebuild build -configuration Release -scheme "FairApp" -sdk "iphonesimulator" -destination "platform=iOS Simulator,name=iPad (8th generation)" 

      - name: Test macOS FairCore
        if: false # not configured for testing
        run: xcodebuild test -configuration Debug -scheme "FairCore" -sdk "macosx" -destination "platform=macosx"

      - name: Build macOS FairApp
        run: xcodebuild build -configuration Release -scheme "FairApp" -sdk "macosx" -destination "platform=macosx"

      - name: Generate docbuild
        run: |
          # see: https://fair-ground.github.io/Fair/documentation/faircore/index.html
          mkdir -p docs
          mkdir -p docbuild/output

          xcodebuild docbuild -scheme "FairCore" -destination "platform=macOS" -derivedDataPath docbuild/output/
          xcodebuild docbuild -scheme "FairApp" -destination "platform=macOS" -derivedDataPath docbuild/output/

          cd docbuild/
          git clone https://github.com/DoccZz/docc2html.git
          cd docc2html
          git checkout $(git describe --tags `git rev-list --tags --max-count=1`)

          swift run docc2html --verbose --force ../output/Build/Products/Debug/FairCore.doccarchive ../../docs/
          swift run docc2html --verbose --force ../output/Build/Products/Debug/FairApp.doccarchive ../../docs/

      - name: Update Docs
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true

  ci-windows:
    runs-on: windows-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - uses: seanmiddleditch/gha-setup-vsdevenv@master
      - name: Install swift-5.5
        run: |
          Install-Binary -Url "https://swift.org/builds/swift-5.5-release/windows10/swift-5.5-RELEASE/swift-5.5-RELEASE-windows10.exe" -Name "installer.exe" -ArgumentList ("-q")
      - name: Set Environment Variables
        run: |
          echo "SDKROOT=C:\Library\Developer\Platforms\Windows.platform\Developer\SDKs\Windows.sdk" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "DEVELOPER_DIR=C:\Library\Developer" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      - name: Adjust Paths
        run: |
          echo "C:\Library\Swift-development\bin;C:\Library\icu-67\usr\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: Install Supporting Files
        run: |
          Copy-Item "$env:SDKROOT\usr\share\ucrt.modulemap" -destination "$env:UniversalCRTSdkDir\Include\$env:UCRTVersion\ucrt\module.modulemap"
          Copy-Item "$env:SDKROOT\usr\share\visualc.modulemap" -destination "$env:VCToolsInstallDir\include\module.modulemap"
          Copy-Item "$env:SDKROOT\usr\share\visualc.apinotes" -destination "$env:VCToolsInstallDir\include\visualc.apinotes"
          Copy-Item "$env:SDKROOT\usr\share\winsdk.modulemap" -destination "$env:UniversalCRTSdkDir\Include\$env:UCRTVersion\um\module.modulemap"

      - name: Get swift version
        run: swift --version # Swift 5.5?

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run fairtool
        run: |
          swift run fairtool welcome

      - name: Fair Tests
        if: false
        # there seems to be a problem with linking a project that
        # contains both a main.swift (fairtool) and test cases
        # (that have their own main() created): 
        # lld-link: error: duplicate symbol: main
        # >>> defined at D:\a\Fair\Fair\.build\x86_64-unknown-windows-msvc\debug\FairPackageTests.build\main.swift.o
        # >>> defined at D:\a\Fair\Fair\.build\x86_64-unknown-windows-msvc\debug\FairTool.build\main.swift.o
        # clang: error: linker command failed with exit code 1 (use -v to see invocation)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          swift test 

