##############################################################################
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################

name: Fair CI

on:
  push:
    branches: [ main ]
  pull_request_target:
    branches:
      - '*'
  schedule:
    - cron: '0 0,12 * * *'

jobs:
  ci-linux:
    runs-on: ubuntu-latest 
    timeout-minutes: 10

    steps:
      - name: Install Swift 5.5
        uses: marcprux/setup-swift@main
        with:
          swift-version: "5.5"

      - name: Get swift version
        run: swift --version # Swift 5.5?

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: swift test

  ci-macOS:
    # runs-on: linux # TODO: Swift 5.5; maybe dev1an/setup-swift@swift-5.5
    runs-on: macos-11
    env:
      #DEVELOPER_DIR: /Applications/Xcode_13.0.app/Contents/Developer
      DEVELOPER_DIR: /Applications/Xcode_13.0_beta.app/Contents/Developer

    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: FairTool
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: xcrun swift run fairtool welcome

      - name: Run Tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: xcrun swift test
 
      - name: Test iOS FairCore
        if: false 
        run: xcodebuild test -configuration Debug -scheme "FairCore" -sdk "iphonesimulator" -destination "platform=iOS Simulator,name=iPad (8th generation)" 

      - name: Build iOS FairApp
        run: xcodebuild build -configuration Release -scheme "FairApp" -sdk "iphonesimulator" -destination "platform=iOS Simulator,name=iPad (8th generation)" 

      - name: Test macOS FairCore
        if: false 
        run: xcodebuild test -configuration Debug -scheme "FairCore" -sdk "macosx" -destination "platform=macosx"

      - name: Build macOS FairApp
        run: xcodebuild build -configuration Release -scheme "FairApp" -sdk "macosx" -destination "platform=macosx"


