##############################################################################
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################

name: Fair CI

on:
  push:
    branches: [ main ]
  pull_request_target:
    branches:
      - '*'
  schedule:
    - cron: '0 0,12 * * *'

jobs:
  ci-linux:
    runs-on: ubuntu-latest 

    steps:
      - name: Get swift version
        run: swift --version 

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run fairtool
        run: |
          swift run fairtool welcome

      - name: Fair Tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: swift test

      - name: Generate docs
        if: false # needs swift 5.6
        run: |
          swift package --allow-writing-to-directory ./docs generate-documentation --target FairCore --target FairApp --output-path ./docs --transform-for-static-hosting --hosting-base-path api

      - name: Update Docs
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true

  ci-macOS-12:
    runs-on: macos-12
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.3.app/Contents/Developer
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run fairtool
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: xcrun swift run fairtool welcome

      - name: Fair Tests
        run: xcrun swift test
 
      - name: Test iOS FairCore
        if: false # not configured for testing
        run: xcodebuild test -configuration Debug -scheme "FairCore" -sdk "iphonesimulator" -destination "platform=iOS Simulator,name=iPhone 13" 

      - name: Build iOS FairApp
        run: xcodebuild build -configuration Release -scheme "FairApp" -sdk "iphonesimulator" -destination "platform=iOS Simulator,name=iPhone 13" 

      - name: Test macOS FairCore
        if: false # not configured for testing
        run: xcodebuild test -configuration Debug -scheme "FairCore" -sdk "macosx" -destination "platform=macosx"

      - name: Build macOS FairApp
        run: xcodebuild build -configuration Release -scheme "FairApp" -sdk "macosx" -destination "platform=macosx"

  ci-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-5.5-release
          tag: 5.5-RELEASE
      - name: Run fairtool
        # A long-standing Windows glitch is the following error (see https://github.com/compnerd/swift-win32/issues/327):
        # TSCUtility/Triple.swift:154: Fatal error: could not determine host triple: malformed
        # So we re-try a few times…
        run: |
          swift run fairtool welcome || swift run fairtool welcome || swift run fairtool welcome || swift run fairtool welcome
      - name: Disable CLI
        # there seems to be a problem with linking a project that
        # contains both a main.swift (fairtool) and test cases
        # (that have their own main() created):
        # lld-link: error: duplicate symbol: main
        # >>> defined at D:\a\Fair\Fair\.build\x86_64-unknown-windows-msvc\debug\FairPackageTests.build\main.swift.o
        # >>> defined at D:\a\Fair\Fair\.build\x86_64-unknown-windows-msvc\debug\FairTool.build\main.swift.o
        # clang: error: linker command failed with exit code 1 (use -v to see invocation)
        run: |
          # swift test on windows fail if there is another main
          # so excise references to FairTool from the package
          mv Package.swift Package.swift.old
          grep -v "FairTool" Package.swift.old > Package.swift
      - name: Fair Tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          swift test 

