##############################################################################
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################

name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request_target:
    branches:
      - '*'
  schedule:
    - cron: '0 0,12 * * *'

jobs:
  ci-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    env:
      FAIRHUB_API_SKIP: true # used by tests to determine load
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Get swift version
        run: swift --version 

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run fairtool
        run: |
          swift run fairtool version

      - name: Fair Test Linux (Debug)
        run: swift test -v --configuration debug

      - name: Fair Test Linux (Release)
        run: swift test -v --configuration release -Xswiftc -enable-testing

      - name: Check fairtool formula
        if: false
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install fair-ground/tool/fairtool-head
          brew test fairtool-head
          fairtool-head version

  ci-macOS:
    runs-on: macos-12
    timeout-minutes: 45
    env:
      DEVELOPER_DIR: /Applications/Xcode_14.1.app/Contents/Developer
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      FAIRHUB_API_SKIP: true # used by tests to determine load

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run fairtool
        run: xcrun swift run fairtool version

      - name: Fair Tests
        run: xcrun swift test
 
      - name: Test iOS (Debug)
        run: xcodebuild -configuration Debug -scheme "Fair-Package" -sdk "iphonesimulator" -destination "platform=iOS Simulator,name=iPhone 14"

      - name: Test iOS (Release)
        run: xcodebuild -configuration Release -scheme "Fair-Package" -sdk "iphonesimulator" -destination "platform=iOS Simulator,name=iPhone 14"

      - name: Test macOS (Debug)
        run: xcodebuild test -configuration Debug -scheme "Fair-Package" -sdk "macosx" -destination "platform=macosx"

      - name: Build macOS (Release)
        run: xcodebuild test -configuration Release -scheme "Fair-Package" -sdk "macosx" -destination "platform=macosx"

      - name: Check fairtool formula
        run: |
          brew install fair-ground/tool/fairtool-head
          brew test fairtool-head
          fairtool-head version
          #fairtool-head app fork App-Name
          #fairtool-head app config App-Name
          #fairtool-head app release App-Name
          #fairtool-head app integrate App-Name

