##############################################################################
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################

# This workflow is run in a fork of https://www.github.com/appfair/App.git
# It will setup a new release with the specified version by tagging it
# with the specified semantic release. 
name: "Configure App Fair App"
on:
  workflow_call:
    inputs:
      # the name of the fairground organization (e.g., "appfair")
      fairground:
        type: string
        required: true
      # the semver tag to use to create the release
      version:
        type: string
        required: true
      appname:
        type: string
        required: true

jobs:
  configure:
    name: "Configure App"
    runs-on: ubuntu-latest

    steps:
      - name: "Setup App"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
          echo "ORGNAME=${{ github.repository_owner }}" >> $GITHUB_ENV
          echo "COMMITHASH=${{ github.sha }}" >> $GITHUB_ENV
          echo "FAIR_APP_ARTIFACT=${{ github.repository_owner }}" >> $GITHUB_ENV
          echo "PRODUCT_NAME=$(echo ${{ github.repository_owner }} | tr '-' ' ')" >> $GITHUB_ENV
          echo "BUNDLE_ID=app.$(echo ${{ github.repository_owner }})" >> $GITHUB_ENV

      - name: "Checkout ${{ env.PRODUCT_NAME }}"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: "Release ${{env.BUNDLE_ID}} ${{ inputs.version }}"
        if: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Creating release ${{env.BUNDLE_ID}} ${{ inputs.version }}"

          echo 'PRODUCT_NAME = ${{ env.PRODUCT_NAME }}' >> AppFairApp.xcconfig
          echo 'PRODUCT_BUNDLE_IDENTIFIER = ${{ env.BUNDLE_ID }}' >> AppFairApp.xcconfig
          echo 'MARKETING_VERSION = ${{ inputs.version }}' >> AppFairApp.xcconfig

          git config --global user.name 'fair-ground action'
          git config --global user.email 'fair-ground@users.noreply.github.com'

          git add AppFairApp.xcconfig
          git commit -m "Configure App version ${{ inputs.version }}"
          git push


