name: Publish

on:
  release:
    types: [published]

jobs:
  formula:
    name: Update Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - name: Update the Homebrew formula with latest release
        uses: NSHipster/update-homebrew-formula-action@main
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_FAIRTOOL_PUBLISH_TOKEN }}
        with:
          repository: fair-ground/Fair
          tap: appfair/homebrew-app
          formula: Formula/fairtool.rb

