name: Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    name: Create GitHub release

    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      current_version: ${{ steps.get_version.outputs.current_version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=current_version::${GITHUB_REF#refs/tags/}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: contains(github.ref, '-')

      - name: Update Homebrew formula with latest release
        uses: NSHipster/update-homebrew-formula-action@main
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_FAIRTOOL_PUBLISH_TOKEN }}
        with:
          repository: fair-ground/Fair
          tap: appfair/homebrew-app
          formula: Formula/fairtool.rb

  bottle_macos:
    name: Homebrew bottle (macOS)
    runs-on: macos-12
    needs: [release]
    steps:
      - name: Build bottle
        run: |
          brew tap appfair/app
          brew install --build-bottle --verbose appfair/app/fairtool
          brew bottle fairtool --no-rebuild

      - name: Upload bottle
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ./fairtool--${{ needs.release.outputs.current_version }}.monterey.bottle.tar.gz
          asset_name: fairtool-${{ needs.release.outputs.current_version }}.monterey.bottle.tar.gz
          asset_content_type: application/gzip

  bottle_linux:
    name: Homebrew bottle (linux)
    runs-on: ubuntu-latest
    needs: [release]
    steps:
      - name: Build bottle
        run: |
          brew tap appfair/app
          brew install --build-bottle --verbose appfair/app/fairtool
          brew bottle fairtool --no-rebuild

      - name: Upload bottle
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ./fairtool--${{ needs.release.outputs.current_version }}.x86_64_linux.bottle.tar.gz
          asset_name: fairtool-${{ needs.release.outputs.current_version }}.x86_64_linux.bottle.tar.gz
          asset_content_type: application/gzip

  update_bottle:
    name: Add bottles to formula
    runs-on: ubuntu-latest
    needs: [bottle_macos, bottle_linux]
    steps:
      - uses: NSHipster/update-homebrew-formula-action@main
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_FAIRTOOL_PUBLISH_TOKEN }}
        with:
          repository: fair-ground/Fair
          tap: appfair/homebrew-app
          formula: Formula/fairtool.rb
          message: |
              Add bottles for fairtool ${{ needs.release.outputs.current_version }}


